version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - T:dependencies
    groups:
      # Group patch updates into a single PR
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
      # Group minor updates into a single PR
      minor-updates:
        applies-to: version-updates
        update-types:
          - "minor"
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build"
      include: "scope"
    labels:
      - T:dependencies
    groups:
      # Group patch updates into a single PR
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
      # Group minor updates into a single PR
      minor-updates:
        applies-to: version-updates
        update-types:
          - "minor"
