[global]
log_level = 'debug'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false

[rest]
enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'gm'
type = 'CosmosSdk'
rpc_addr = 'http://gm-chain:26757'
grpc_addr = 'http://gm-chain:9190'
rpc_timeout = '10s'
trusted_node = false
account_prefix = 'gm'
key_name = 'gm-relayer'
key_store_type = 'Test'
store_prefix = 'ibc'
default_gas = 200000
max_gas = 2000000
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 2097152
max_grpc_decoding_size = 33554432
clock_drift = '5s'
max_block_time = '30s'
ccv_consumer_chain = false
memo_prefix = ''
sequential_batch_tx = false

[chains.event_source]
mode = 'pull'
interval = '1s'

[chains.trust_threshold]
numerator = '1'
denominator = '3'

[chains.gas_price]
price = 10.0
denom = 'stake'

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-*'],
]

[chains.address_type]
derivation = 'cosmos'

[[chains]]
id = 'gaia-local'
type = 'CosmosSdk'
rpc_addr = 'http://gaia-chain:26657'
grpc_addr = 'http://gaia-chain:9090'
rpc_timeout = '10s'
trusted_node = false
account_prefix = 'cosmos'
key_name = 'gaia-relayer'
key_store_type = 'Test'
store_prefix = 'ibc'
default_gas = 200000
max_gas = 2000000
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 2097152
max_grpc_decoding_size = 33554432
clock_drift = '5s'
max_block_time = '30s'
ccv_consumer_chain = false
memo_prefix = ''
sequential_batch_tx = false

[chains.event_source]
mode = 'pull'
interval = '1s'

[chains.trust_threshold]
numerator = '1'
denominator = '3'

[chains.gas_price]
price = 10.0
denom = 'stake'

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-*'],
]

[chains.address_type]
derivation = 'cosmos'
