package integration_test

import (
	"context"
	"cosmossdk.io/math"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"github.com/celestiaorg/tastora/framework/docker"
	"github.com/celestiaorg/tastora/framework/docker/container"
	"github.com/celestiaorg/tastora/framework/testutil/sdkacc"
	"github.com/celestiaorg/tastora/framework/types"
	"github.com/cometbft/cometbft/crypto"
	cmtjson "github.com/cometbft/cometbft/libs/json"
	cmprivval "github.com/cometbft/cometbft/privval"
	sdk "github.com/cosmos/cosmos-sdk/types"
	"github.com/cosmos/cosmos-sdk/types/module/testutil"
	"github.com/cosmos/cosmos-sdk/x/auth"
	"github.com/cosmos/cosmos-sdk/x/bank"
	banktypes "github.com/cosmos/cosmos-sdk/x/bank/types"
	"github.com/libp2p/go-libp2p/core/peer"
	"github.com/moby/moby/client"
	"github.com/multiformats/go-multihash"
	"github.com/stretchr/testify/suite"
	"go.uber.org/zap/zaptest"
)

const (
	celestiaAppTag   = "v4.0.10"
	celestiaNodeTag  = "v0.23.5"
	celestiaAppRepo  = "ghcr.io/celestiaorg/celestia-app"
	celestiaNodeRepo = "ghcr.io/celestiaorg/celestia-node"
)

// DockerIntegrationTestSuite provides common functionality for integration tests using Docker
type DockerIntegrationTestSuite struct {
	suite.Suite

	dockerClient  *client.Client
	networkID     string
	celestiaChain *docker.Chain
	daNetwork     types.DataAvailabilityNetwork
	evolveChain   *docker.Chain
	bridgeNode    types.DANode
}

// SetupTest initializes the Docker environment for each test
// celestia is deployed, a single bridge node and the rollkit chain.
func (s *DockerIntegrationTestSuite) SetupTest() {
	ctx := context.Background()
	s.dockerClient, s.networkID = docker.DockerSetup(s.T())

	s.celestiaChain = s.CreateCelestiaChain(ctx)
	s.T().Log("Celestia app chain started")

	s.bridgeNode = s.CreateDANetwork(ctx)
	s.T().Log("Bridge node started")

	s.evolveChain = s.CreateEvolveChain(ctx)
	s.T().Log("Evolve chain started")
}

// CreateCelestiaChain sets up a Celestia app chain for DA and stores it in the suite
func (s *DockerIntegrationTestSuite) CreateCelestiaChain(ctx context.Context) *docker.Chain {
	testEncCfg := testutil.MakeTestEncodingConfig(auth.AppModuleBasic{}, bank.AppModuleBasic{})
	celestia, err := docker.NewChainBuilder(s.T()).
		WithEncodingConfig(&testEncCfg).
		WithDockerClient(s.dockerClient).
		WithDockerNetworkID(s.networkID).
		WithImage(container.NewImage(celestiaAppRepo, celestiaAppTag, "10001:10001")).
		WithAdditionalStartArgs(
			"--force-no-bbr",
			"--grpc.enable",
			"--grpc.address", "0.0.0.0:9090",
			"--rpc.grpc_laddr=tcp://0.0.0.0:9098",
			"--timeout-commit", "1s",
			"--minimum-gas-prices", "0.000001utia",
		).
		WithNode(docker.NewChainNodeConfigBuilder().Build()).
		Build(ctx)

	s.Require().NoError(err)

	err = celestia.Start(ctx)
	s.Require().NoError(err)
	return celestia
}

// CreateDANetwork sets up the DA network with bridge and full nodes and stores it in the suite
func (s *DockerIntegrationTestSuite) CreateDANetwork(ctx context.Context) types.DANode {
	config := &docker.Config{
		Logger:          zaptest.NewLogger(s.T()),
		DockerClient:    s.dockerClient,
		DockerNetworkID: s.networkID,
		DataAvailabilityNetworkConfig: &docker.DataAvailabilityNetworkConfig{
			Image:           container.NewImage(celestiaNodeRepo, celestiaNodeTag, "10001:10001"),
			BridgeNodeCount: 1,
		},
	}

	provider := docker.NewProvider(*config, s.T())
	daNetwork, err := provider.GetDataAvailabilityNetwork(ctx)
	s.Require().NoError(err)

	s.daNetwork = daNetwork

	genesisHash, err := getGenesisHash(ctx, s.celestiaChain)
	s.Require().NoError(err)

	bridgeNodes := daNetwork.GetBridgeNodes()
	s.Require().NotEmpty(bridgeNodes, "no bridge nodes available")

	bridgeNode := bridgeNodes[0]

	chainID := s.celestiaChain.GetChainID()
	celestiaNodeHostname, err := s.celestiaChain.GetNodes()[0].GetInternalHostName(ctx)
	s.Require().NoError(err)

	err = bridgeNode.Start(ctx,
		types.WithChainID(chainID),
		// my-key is the name of the keyring generated by the bridge node, we can fund this key so that we can submit blobs.
		types.WithAdditionalStartArguments("--p2p.network", chainID, "--core.ip", celestiaNodeHostname, "--rpc.addr", "0.0.0.0", "--keyring.keyname", "my-key"),
		types.WithEnvironmentVariables(map[string]string{
			"CELESTIA_CUSTOM": types.BuildCelestiaCustomEnvVar(chainID, genesisHash, ""),
			"P2P_NETWORK":     chainID,
		}),
	)
	s.Require().NoError(err)

	// Fund the bridge node DA wallet to enable blob submission
	s.fundBridgeNodeWallet(ctx, bridgeNode)

	return bridgeNode
}

// CreateEvolveChain sets up the rollkit chain connected to the DA network and returns it
func (s *DockerIntegrationTestSuite) CreateEvolveChain(ctx context.Context) *docker.Chain {
	// Get DA connection details
	authToken, err := s.bridgeNode.GetAuthToken()
	s.Require().NoError(err)

	bridgeRPCAddress, err := s.bridgeNode.GetInternalRPCAddress()
	s.Require().NoError(err)

	daAddress := fmt.Sprintf("http://%s", bridgeRPCAddress)

	celestiaHeight, err := s.celestiaChain.Height(ctx)
	s.Require().NoError(err)
	daStartHeight := fmt.Sprintf("%d", celestiaHeight)

	// bank and auth modules required to deal with bank send tx's
	testEncCfg := testutil.MakeTestEncodingConfig(auth.AppModuleBasic{}, bank.AppModuleBasic{})
	// Create chain with only the aggregator node initially
	evolveChain, err := docker.NewChainBuilder(s.T()).
		WithEncodingConfig(&testEncCfg).
		WithImage(getEvolveAppContainer()).
		WithDenom("stake").
		WithDockerClient(s.dockerClient).
		WithName("evolve").
		WithDockerNetworkID(s.networkID).
		WithChainID("evolve-test").
		WithBech32Prefix("gm").
		WithBinaryName("gmd").
		// explicitly set 0 gas so that we can make exact assertions when sending balances.
		WithGasPrices(fmt.Sprintf("0.00%s", "stake")).
		WithNodes(
			docker.NewChainNodeConfigBuilder().
				// Create aggregator node with rollkit-specific start arguments
				WithAdditionalStartArgs(
					"--evnode.node.aggregator",
					"--evnode.signer.passphrase", "12345678",
					"--evnode.da.address", daAddress,
					"--evnode.da.gas_price", "0.000001",
					"--evnode.da.auth_token", authToken,
					"--evnode.rpc.address", "0.0.0.0:7331",
					"--evnode.da.header_namespace", "ev-header",
					"--evnode.da.data_namespace", "ev-data",
					"--evnode.da.start_height", daStartHeight,
					"--evnode.p2p.listen_address", "/ip4/0.0.0.0/tcp/36656",
					"--log_level", "*:info",
				).
				WithPostInit(addSingleSequencer).
				Build(),
		).
		Build(ctx)

	s.Require().NoError(err)

	// Start the aggregator node first so that we can query the p2p
	err = evolveChain.Start(ctx)
	s.Require().NoError(err)

	aggregatorPeer := s.GetNodeMultiAddr(ctx, evolveChain.GetNode())
	s.T().Logf("Aggregator peer: %s", aggregatorPeer)

	s.T().Logf("Adding first follower node...")
	s.addFollowerNode(ctx, evolveChain, daAddress, authToken, daStartHeight)
	s.T().Logf("Adding second follower node...")
	s.addFollowerNode(ctx, evolveChain, daAddress, authToken, daStartHeight)

	return evolveChain
}

// GetNodeMultiAddr extracts the multiaddr from a rollkit chain node
// Returns the multiaddr in the format: /ip4/{IP}/tcp/36656/p2p/{PEER_ID}
func (s *DockerIntegrationTestSuite) GetNodeMultiAddr(ctx context.Context, node *docker.ChainNode) string {
	// Get the node ID
	nodeID, err := node.NodeID(ctx)
	s.Require().NoError(err)
	s.Require().NotEmpty(nodeID, "node ID is empty")

	// Get the node's internal IP address
	nodeIP, err := node.GetInternalIP(ctx)
	s.Require().NoError(err)

	// Convert hex node ID to libp2p peer ID
	nodeIDBytes, err := hex.DecodeString(nodeID)
	s.Require().NoError(err)

	// Create a multihash from the node ID bytes (using identity hash since it's already hashed)
	mh, err := multihash.Sum(nodeIDBytes, multihash.IDENTITY, -1)
	s.Require().NoError(err)

	// Create peer ID from multihash
	peerID, err := peer.IDFromBytes(mh)
	s.Require().NoError(err)

	// Construct the multiaddr with default rollkit P2P port
	multiAddr := fmt.Sprintf("/ip4/%s/tcp/36656/p2p/%s", nodeIP, peerID.String())

	return multiAddr
}

// addFollowerNode adds a follower node to the evolve chain.
func (s *DockerIntegrationTestSuite) addFollowerNode(ctx context.Context, evolveChain *docker.Chain, daAddress, authToken, daStartHeight string) {
	err := evolveChain.AddNode(ctx, docker.NewChainNodeConfigBuilder().
		WithAdditionalStartArgs(
			"--evnode.da.address", daAddress,
			"--evnode.da.gas_price", "0.000001",
			"--evnode.da.auth_token", authToken,
			"--evnode.rpc.address", "0.0.0.0:7331",
			"--evnode.da.header_namespace", "ev-header",
			"--evnode.da.data_namespace", "ev-data",
			"--evnode.da.start_height", daStartHeight,
			"--evnode.p2p.listen_address", "/ip4/0.0.0.0/tcp/36656",
			//"--evnode.p2p.peers", aggregatorPeer, // TODO uncomment to enable P2P, seems broken right now
			"--log_level", "*:debug",
		).
		Build())
	s.Require().NoError(err)
}

// getGenesisHash retrieves the genesis hash from the celestia chain
func getGenesisHash(ctx context.Context, chain types.Chain) (string, error) {
	node := chain.GetNodes()[0]
	c, err := node.GetRPCClient()
	if err != nil {
		return "", fmt.Errorf("failed to get node client: %w", err)
	}

	first := int64(1)
	block, err := c.Block(ctx, &first)
	if err != nil {
		return "", fmt.Errorf("failed to get block: %w", err)
	}

	genesisHash := block.Block.Header.Hash().String()
	if genesisHash == "" {
		return "", fmt.Errorf("genesis hash is empty")
	}

	return genesisHash, nil
}

// sendFunds sends funds from one wallet to another using bank transfer
func (s *DockerIntegrationTestSuite) sendFunds(ctx context.Context, chain *docker.Chain, fromWallet, toWallet types.Wallet, amount sdk.Coins, nodeIdx int) error {
	fromAddress, err := sdkacc.AddressFromWallet(fromWallet)
	if err != nil {
		return fmt.Errorf("failed to get sender address: %w", err)
	}

	toAddress, err := sdkacc.AddressFromWallet(toWallet)
	if err != nil {
		return fmt.Errorf("failed to get destination address: %w", err)
	}

	chainNode := chain.GetNodes()[nodeIdx]
	broadcaster := docker.NewBroadcasterForNode(chain, chainNode.(*docker.ChainNode))

	msg := banktypes.NewMsgSend(fromAddress, toAddress, amount)
	resp, err := broadcaster.BroadcastMessages(ctx, fromWallet, msg)
	if err != nil {
		return fmt.Errorf("failed to broadcast transaction: %w", err)
	}

	if resp.Code != 0 {
		return fmt.Errorf("transaction failed with code %d: %s", resp.Code, resp.RawLog)
	}

	return nil
}

// addSingleSequencer modifies the genesis file to ensure single sequencer setup
func addSingleSequencer(ctx context.Context, node *docker.ChainNode) error {
	genesisBz, err := node.ReadFile(ctx, "config/genesis.json")
	if err != nil {
		return fmt.Errorf("failed to read genesis.json: %w", err)
	}

	pubKey, err := getPubKey(ctx, node)
	if err != nil {
		return fmt.Errorf("failed to get pubkey: %w", err)
	}

	var genDoc map[string]interface{}
	if err := json.Unmarshal(genesisBz, &genDoc); err != nil {
		return fmt.Errorf("failed to parse genesis.json: %w", err)
	}

	// set consensus validators to only include the first validator
	consensus, ok := genDoc["consensus"].(map[string]interface{})
	if !ok {
		return fmt.Errorf("genesis.json does not contain a valid 'consensus' object")
	}
	consensus["validators"] = []map[string]interface{}{
		{
			"name":    "Rollkit Sequencer",
			"address": pubKey.Address(),
			"pub_key": map[string]interface{}{
				"type":  "tendermint/PubKeyEd25519",
				"value": pubKey.Bytes(),
			},
			"power": "5",
		},
	}

	updatedGenesis, err := json.MarshalIndent(genDoc, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal genesis: %w", err)
	}

	err = node.WriteFile(ctx, "config/genesis.json", updatedGenesis)
	if err != nil {
		return fmt.Errorf("failed to write genesis.json: %w", err)
	}

	return nil
}

// getPubKey returns the validator public key
func getPubKey(ctx context.Context, chainNode *docker.ChainNode) (crypto.PubKey, error) {
	keyJSONBytes, err := chainNode.ReadFile(ctx, "config/priv_validator_key.json")
	if err != nil {
		return nil, err
	}
	var pvKey cmprivval.FilePVKey
	if err = cmtjson.Unmarshal(keyJSONBytes, &pvKey); err != nil {
		return nil, fmt.Errorf("failed to unmarshal priv_validator_key.json: %w", err)
	}
	return pvKey.PubKey, nil
}

// fundBridgeNodeWallet funds the bridge node's DA wallet for blob submission
func (s *DockerIntegrationTestSuite) fundBridgeNodeWallet(ctx context.Context, bridgeNode types.DANode) {
	// hack to get around global, need to set the address prefix before use.
	sdk.GetConfig().SetBech32PrefixForAccount("celestia", "celestiapub")

	s.T().Log("Funding bridge node DA wallet...")
	fundingWallet := s.celestiaChain.GetFaucetWallet()

	// Get the bridge node's wallet
	bridgeWallet, err := bridgeNode.GetWallet()
	s.Require().NoError(err)

	// fund the bridge node wallet
	daFundingAmount := sdk.NewCoins(sdk.NewCoin("utia", math.NewInt(10_000_000)))
	err = s.sendFunds(ctx, s.celestiaChain, fundingWallet, bridgeWallet, daFundingAmount, 0)
	s.Require().NoError(err)
}
