services:
  binaries:
    build:
      context: ../../..
      dockerfile: .github/compose/docker/Dockerfile.binaries
    image: integration-tests-binaries:latest
    container_name: integration-test-binaries
    command: ["true"]
    networks:
      - ibc-test

  # Local Data Availability (DA) service
  local-da:
    build:
      context: ../../..
      dockerfile: .github/compose/docker/Dockerfile.local-da
      args:
        EV_NODE_REF: ${EV_NODE_REF:-main}
    container_name: rollkit-local-da
    command: ["local-da", "-listen-all"]
    ports:
      - "7980:7980"
    networks:
      - ibc-test

networks:
  ibc-test:
    driver: bridge
