services:
  binaries:
    build:
      context: ../../..
      dockerfile: .github/compose/docker/Dockerfile.binaries
    image: integration-tests-binaries:latest
    container_name: integration-test-binaries
    command: ["true"]
    networks:
      - ibc-test

  local-da:
    build:
      context: ../../..
      dockerfile: .github/compose/docker/Dockerfile.local-da
      args:
        EV_NODE_REF: ${EV_NODE_REF:-main}
    image: ev-local-da:latest
    container_name: rollkit-local-da
    command: ["local-da", "-listen-all"]
    ports:
      - "7980:7980"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "7980"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ibc-test

networks:
  ibc-test:
    driver: bridge
