name: Attester Mode Integration Test

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    name: Setup Evolve Chain (scaffold & build)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DO_NOT_TRACK: true
      EVNODE_VERSION: "v1.0.0-beta.2.0.20250908090838-0584153217ed"
      EVNODE_DA_VERSION: "v1.0.0-beta.1"
      IGNITE_VERSION: "v29.3.1"
      IGNITE_EVOLVE_APP_VERSION: "main"
      GAIA_VERSION: "v25.1.0"

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run integration tests (compose orchestrator)
        env:
          VERBOSE: "true"
        run: |
          set -euo pipefail
          bash .github/integration-tests/run-integration-tests.sh --timeout 900

      - name: Upload integration logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-logs
          path: .github/integration-tests/logs/
          if-no-files-found: warn
