name: integration_attester_prep

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prep:
    name: Preparation (tools, Docker, Ignite)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DO_NOT_TRACK: true
      IGNITE_VERSION: "v29.3.1"
      EVNODE_VERSION: "v1.0.0-beta.2.0.20250908090838-0584153217ed"
      IGNITE_EVOLVE_APP_VERSION: "main"

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Install Ignite CLI
        run: |
          echo "Installing Ignite CLI ${IGNITE_VERSION}"
          curl -sSL https://get.ignite.com/cli@$IGNITE_VERSION! | bash

      - name: Scaffold Evolve Chain
        run: |
          echo "Scaffolding chain gm and adding evolve app (${IGNITE_EVOLVE_APP_VERSION})"
          ignite scaffold chain gm --no-module --skip-git --address-prefix gm
          cd gm
          ignite app install github.com/ignite/apps/evolve@$IGNITE_EVOLVE_APP_VERSION
          ignite evolve add